//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class DAL {
        
        private string connectionString;
        
        public DAL(string connectionString) {
            this.connectionString = connectionString;
        }
        
        public DAL(string server, string database) {
            this.connectionString = string.Format("Server={0};Database={1};Trusted_Connection=True;", server, database);
        }
        
        public DAL(string server, string database, string user, string pass) {
            this.connectionString = string.Format("Server={0};Database={1};User ID={2};Password={3};Trusted_Connection=False", server, database,user,pass);
        }
        
        public virtual string ConnectionString {
            get {
                return this.connectionString;
            }
            set {
                this.connectionString = value;
            }
        }
        
        public virtual System.Data.DataTable GetData(System.Data.SqlClient.SqlCommand cmd) {
            System.Data.SqlClient.SqlConnection con;
            con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
            cmd.Connection = con;
            try {
                con.Open();
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual int ExecNonQuery(System.Data.SqlClient.SqlCommand cmd) {
            System.Data.SqlClient.SqlConnection con;
            con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
            cmd.Connection = con;
            try {
                int output;
                con.Open();
                output = cmd.ExecuteNonQuery();
                con.Close();
                return output;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return -1;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return -1;
            }
        }
        
        public virtual System.Data.DataTable sp_upgraddiagrams() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_upgraddiagrams";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_helpdiagrams() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_helpdiagrams";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_helpdiagramdefinition() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_helpdiagramdefinition";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_creatediagram() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_creatediagram";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_renamediagram() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_renamediagram";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_alterdiagram() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_alterdiagram";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
        
        public virtual System.Data.DataTable sp_dropdiagram() {
            try {
                System.Data.SqlClient.SqlConnection con;
                con = new System.Data.SqlClient.SqlConnection(this.ConnectionString);
                System.Data.SqlClient.SqlCommand cmd;
                cmd = new System.Data.SqlClient.SqlCommand();
                cmd.CommandText = "sp_dropdiagram";
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Connection = con;
                System.Data.SqlClient.SqlDataReader dr;
                System.Data.DataTable dt;
                dt = new System.Data.DataTable();
                con.Open();
                dr = cmd.ExecuteReader();
                dt.Load(dr);
                con.Close();
                return dt;
            }
            catch (System.Data.SqlClient.SqlException ex) {
                string errorTitle = "Error ";
                string numError = ex.Number.ToString();
                errorTitle = errorTitle + numError;
                System.Windows.Forms.MessageBox.Show(ex.Message, errorTitle);
                return null;
            }
            catch (System.Exception ex) {
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error!");
                return null;
            }
        }
    }
}
