//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class AdvertisingObjectives {
        
        private object _AdvertisingObjectivesID;
        
        private object _AdvertisingObjectivesTitle;
        
        private object _AdvertisingObjectivesPage;
        
        private object _AdvertisingObjectivesFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;
        
        public AdvertisingObjectives() {
        }
        
        public virtual object AdvertisingObjectivesID {
            get {
                return this._AdvertisingObjectivesID;
            }
            set {
                this._AdvertisingObjectivesID = value;
            }
        }
        
        public virtual object AdvertisingObjectivesTitle {
            get {
                return this._AdvertisingObjectivesTitle;
            }
            set {
                this._AdvertisingObjectivesTitle = value;
            }
        }
        
        public virtual object AdvertisingObjectivesPage {
            get {
                return this._AdvertisingObjectivesPage;
            }
            set {
                this._AdvertisingObjectivesPage = value;
            }
        }
        
        public virtual object AdvertisingObjectivesFileName {
            get {
                return this._AdvertisingObjectivesFileName;
            }
            set {
                this._AdvertisingObjectivesFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class AdvertisingObjectivesCollection : System.Collections.CollectionBase {
        
        public virtual AdvertisingObjectives this[int index] {
            get {
                return ((AdvertisingObjectives)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(AdvertisingObjectives Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(AdvertisingObjectives Item) {
            List.Remove(Item);
        }
    }

