//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class AgencyBoard {
        
        private object _AgencyID;
        
        private object _ImageFile;
        
        private object _ImagePath;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        public AgencyBoard() {
        }
        
        public virtual object AgencyID {
            get {
                return this._AgencyID;
            }
            set {
                this._AgencyID = value;
            }
        }
        
        public virtual object ImageFile {
            get {
                return this._ImageFile;
            }
            set {
                this._ImageFile = value;
            }
        }
        
        public virtual object ImagePath {
            get {
                return this._ImagePath;
            }
            set {
                this._ImagePath = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
    }
    
    public class AgencyBoardCollection : System.Collections.CollectionBase {
        
        public virtual AgencyBoard this[int index] {
            get {
                return ((AgencyBoard)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(AgencyBoard Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(AgencyBoard Item) {
            List.Remove(Item);
        }
    }


