//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Agenda {
        
        private object _AgendaID;
        
        private object _AgendaTitle;
        
        private object _AgendaPage;
        
        private object _AgendaFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        public Agenda() {
        }
        
        public virtual object AgendaID {
            get {
                return this._AgendaID;
            }
            set {
                this._AgendaID = value;
            }
        }
        
        public virtual object AgendaTitle {
            get {
                return this._AgendaTitle;
            }
            set {
                this._AgendaTitle = value;
            }
        }
        
        public virtual object AgendaPage {
            get {
                return this._AgendaPage;
            }
            set {
                this._AgendaPage = value;
            }
        }
        
        public virtual object AgendaFileName {
            get {
                return this._AgendaFileName;
            }
            set {
                this._AgendaFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
    }
    
    public class AgendaCollection : System.Collections.CollectionBase {
        
        public virtual Agenda this[int index] {
            get {
                return ((Agenda)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Agenda Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Agenda Item) {
            List.Remove(Item);
        }
    }

