//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Attendees {
        
        private object _AttendeeID;
        
        private object _AttendeeTitle;
        
        private object _AttendeePage;
        
        private object _AttendeeFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        public Attendees() {
        }
        
        public virtual object AttendeeID {
            get {
                return this._AttendeeID;
            }
            set {
                this._AttendeeID = value;
            }
        }
        
        public virtual object AttendeeTitle {
            get {
                return this._AttendeeTitle;
            }
            set {
                this._AttendeeTitle = value;
            }
        }
        
        public virtual object AttendeePage {
            get {
                return this._AttendeePage;
            }
            set {
                this._AttendeePage = value;
            }
        }
        
        public virtual object AttendeeFileName {
            get {
                return this._AttendeeFileName;
            }
            set {
                this._AttendeeFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
    }
    
    public class AttendeesCollection : System.Collections.CollectionBase {
        
        public virtual Attendees this[int index] {
            get {
                return ((Attendees)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Attendees Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Attendees Item) {
            List.Remove(Item);
        }
    }
