//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsagencyBoard {

        public static void Insert(AgencyBoard agencyBoard)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from AgencyBoard", conn);
            conn.Open();
            System.Data.DataTable tbAgencyBoard;
            tbAgencyBoard = new System.Data.DataTable("AgencyBoard");
            adapt.Fill(tbAgencyBoard);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.InsertCommand = mybuild.GetInsertCommand();
           
            
                System.Data.DataRow rowAgencyBoard;
                rowAgencyBoard = tbAgencyBoard.NewRow();
               // rowAgencyBoard["AgencyID"] = agencyBoard.AgencyID;
                rowAgencyBoard["ImageFile"] = agencyBoard.ImageFile;
                rowAgencyBoard["ImagePath"] = agencyBoard.ImagePath;
                rowAgencyBoard["CreatedBy"] = agencyBoard.CreatedBy;
                rowAgencyBoard["CreatedDate"] = agencyBoard.CreatedDate;
                rowAgencyBoard["ModifiedBy"] = agencyBoard.ModifiedBy;
                rowAgencyBoard["ModifiedDate"] = agencyBoard.ModifiedDate;
                tbAgencyBoard.Rows.Add(rowAgencyBoard);
                adapt.Update(tbAgencyBoard);
         
        }
        
        public static void Update(AgencyBoard agencyBoard) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
         

            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from AgencyBoard where  AgencyID = " + agencyBoard.AgencyID + "", conn);
            
            conn.Open();
            System.Data.DataTable tbAgencyBoard;
            tbAgencyBoard = new System.Data.DataTable("AgencyBoard");
            adapt.Fill(tbAgencyBoard);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
        
      
                // Edit methods
                System.Data.DataRow rowAgencyBoard;
                rowAgencyBoard = tbAgencyBoard.Rows[0];
                rowAgencyBoard["AgencyID"] = agencyBoard.AgencyID;
                rowAgencyBoard["ImageFile"] = agencyBoard.ImageFile;
                rowAgencyBoard["ImagePath"] = agencyBoard.ImagePath;    
                rowAgencyBoard["ModifiedBy"] = agencyBoard.ModifiedBy;
                rowAgencyBoard["ModifiedDate"] = agencyBoard.ModifiedDate;
                adapt.Update(tbAgencyBoard);
          
        }

        public static AgencyBoard getAgencyBoard(Int32 AgencyID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
         
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from AgencyBoard where  AgencyID = " + AgencyID + "", conn);
            conn.Open();
            System.Data.DataTable tbAgencyBoard;
            tbAgencyBoard = new System.Data.DataTable("AgencyBoard");
            adapt.Fill(tbAgencyBoard);
            AgencyBoard AgencyBoard;
            AgencyBoard = new AgencyBoard();
            if (tbAgencyBoard.Rows.Count > 0) {
                System.Data.DataRow rowAgencyBoard;
                rowAgencyBoard = tbAgencyBoard.Rows[0];
                AgencyBoard.AgencyID = System.Convert.ToInt32(rowAgencyBoard["AgencyID"]);
                AgencyBoard.ImageFile = System.Convert.ToString(rowAgencyBoard["ImageFile"]);
                AgencyBoard.ImagePath = System.Convert.ToString(rowAgencyBoard["ImagePath"]);
                AgencyBoard.CreatedBy = System.Convert.ToString(rowAgencyBoard["CreatedBy"]);
                AgencyBoard.CreatedDate = System.Convert.ToDateTime(rowAgencyBoard["CreatedDate"]);
                AgencyBoard.ModifiedBy = System.Convert.ToString(rowAgencyBoard["ModifiedBy"]);
                AgencyBoard.ModifiedDate = System.Convert.ToDateTime(rowAgencyBoard["ModifiedDate"]);
                return AgencyBoard;
            }
            else {
                return null;
            }
        }


    }

