//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsadvertisingObjectives {
        
        public static void Update(AdvertisingObjectives advertisingObjectives) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from AdvertisingObjectives where 1=1", conn);
            conn.Open();
            System.Data.DataTable tbAdvertisingObjectives;
            tbAdvertisingObjectives = new System.Data.DataTable("AdvertisingObjectives");
            adapt.Fill(tbAdvertisingObjectives);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbAdvertisingObjectives.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowAdvertisingObjectives;
                rowAdvertisingObjectives = tbAdvertisingObjectives.Rows[0];
                rowAdvertisingObjectives["AdvertisingObjectivesID"] = advertisingObjectives.AdvertisingObjectivesID;
                rowAdvertisingObjectives["AdvertisingObjectivesTitle"] = advertisingObjectives.AdvertisingObjectivesTitle;
                rowAdvertisingObjectives["AdvertisingObjectivesPage"] = advertisingObjectives.AdvertisingObjectivesPage;
                rowAdvertisingObjectives["AdvertisingObjectivesFileName"] = advertisingObjectives.AdvertisingObjectivesFileName;
                rowAdvertisingObjectives["CreatedBy"] = advertisingObjectives.CreatedBy;
                rowAdvertisingObjectives["CreatedDate"] = advertisingObjectives.CreatedDate;
                rowAdvertisingObjectives["ModifiedBy"] = advertisingObjectives.ModifiedBy;
                rowAdvertisingObjectives["ModifiedDate"] = advertisingObjectives.ModifiedDate;
                rowAdvertisingObjectives["PresentationID"] = advertisingObjectives.PresentationID;
                adapt.Update(tbAdvertisingObjectives);
            }
            else {
                System.Data.DataRow rowAdvertisingObjectives;
                rowAdvertisingObjectives = tbAdvertisingObjectives.NewRow();
                rowAdvertisingObjectives["AdvertisingObjectivesID"] = advertisingObjectives.AdvertisingObjectivesID;
                rowAdvertisingObjectives["AdvertisingObjectivesTitle"] = advertisingObjectives.AdvertisingObjectivesTitle;
                rowAdvertisingObjectives["AdvertisingObjectivesPage"] = advertisingObjectives.AdvertisingObjectivesPage;
                rowAdvertisingObjectives["AdvertisingObjectivesFileName"] = advertisingObjectives.AdvertisingObjectivesFileName;
                rowAdvertisingObjectives["CreatedBy"] = advertisingObjectives.CreatedBy;
                rowAdvertisingObjectives["CreatedDate"] = advertisingObjectives.CreatedDate;
                rowAdvertisingObjectives["ModifiedBy"] = advertisingObjectives.ModifiedBy;
                rowAdvertisingObjectives["ModifiedDate"] = advertisingObjectives.ModifiedDate;
                rowAdvertisingObjectives["PresentationID"] = advertisingObjectives.PresentationID;
                tbAdvertisingObjectives.Rows.Add(rowAdvertisingObjectives);
                adapt.Update(tbAdvertisingObjectives);
            }
        }

        public static AdvertisingObjectives getAdvertisingObjectives(Int32 AdvertisingObjectivesID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from AdvertisingObjectives where  AdvertisingObjectivesID = " + AdvertisingObjectivesID + "", conn);
            conn.Open();
            System.Data.DataTable tbAdvertisingObjectives;
            tbAdvertisingObjectives = new System.Data.DataTable("AdvertisingObjectives");
            adapt.Fill(tbAdvertisingObjectives);
            AdvertisingObjectives AdvertisingObjectives;
            AdvertisingObjectives = new AdvertisingObjectives();
            if (tbAdvertisingObjectives.Rows.Count > 0) {
                System.Data.DataRow rowAdvertisingObjectives;
                rowAdvertisingObjectives = tbAdvertisingObjectives.Rows[0];
                AdvertisingObjectives.AdvertisingObjectivesID = System.Convert.ToInt32(rowAdvertisingObjectives["AdvertisingObjectivesID"]);
                AdvertisingObjectives.AdvertisingObjectivesTitle = System.Convert.ToString(rowAdvertisingObjectives["AdvertisingObjectivesTitle"]);
                AdvertisingObjectives.AdvertisingObjectivesPage = System.Convert.ToString(rowAdvertisingObjectives["AdvertisingObjectivesPage"]);
                AdvertisingObjectives.AdvertisingObjectivesFileName = System.Convert.ToString(rowAdvertisingObjectives["AdvertisingObjectivesFileName"]);
                AdvertisingObjectives.CreatedBy = System.Convert.ToString(rowAdvertisingObjectives["CreatedBy"]);
                AdvertisingObjectives.CreatedDate = System.Convert.ToDateTime(rowAdvertisingObjectives["CreatedDate"]);
                AdvertisingObjectives.ModifiedBy = System.Convert.ToString(rowAdvertisingObjectives["ModifiedBy"]);
                AdvertisingObjectives.ModifiedDate = System.Convert.ToDateTime(rowAdvertisingObjectives["ModifiedDate"]);
                AdvertisingObjectives.PresentationID = System.Convert.ToInt32(rowAdvertisingObjectives["PresentationID"]);
                return AdvertisingObjectives;
            }
            else {
                return null;
            }
        }
    }

