//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsclient {
        public static void Insert(Client client)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Client", conn);
            conn.Open();
            System.Data.DataTable tbClient;
            tbClient = new System.Data.DataTable("Client");
            adapt.Fill(tbClient);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            //if (tbClient.Rows.Count > 0)
            //{
            //    // Edit methods
            //    System.Data.DataRow rowClient;
            //    rowClient = tbClient.Rows[0];
            //    rowClient["ClientName"] = client.ClientName;
            //    rowClient["Description"] = client.Description;
            //    rowClient["CompanyID"] = client.CompanyID;
            //    adapt.Update(tbClient);
            //}
            //else
            //{
                System.Data.DataRow rowClient;
                rowClient = tbClient.NewRow();
                //rowClient["ClientID"] = client.ClientID;
                rowClient["ClientName"] = client.ClientName;
                rowClient["Description"] = client.Description;
                rowClient["CompanyID"] = client.CompanyID;
                tbClient.Rows.Add(rowClient);
                adapt.Update(tbClient);
            //}
        }
        public static void Update(Client client) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Client where  ClientID = " + client.ClientID + "", conn);
            conn.Open();
            System.Data.DataTable tbClient;
            tbClient = new System.Data.DataTable("Client");
            adapt.Fill(tbClient);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbClient.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowClient;
                rowClient = tbClient.Rows[0];
                rowClient["ClientName"] = client.ClientName;
                rowClient["Description"] = client.Description;
                rowClient["CompanyID"] = client.CompanyID;
                adapt.Update(tbClient);
            }
            else {
                System.Data.DataRow rowClient;
                rowClient = tbClient.NewRow();
                rowClient["ClientID"] = client.ClientID;
                rowClient["ClientName"] = client.ClientName;
                rowClient["Description"] = client.Description;
                rowClient["CompanyID"] = client.CompanyID;
                tbClient.Rows.Add(rowClient);
                adapt.Update(tbClient);
            }
        }
        
        public static Client getClient(Int32 ClientID) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Client where  ClientID = " + ClientID + "", conn);
            conn.Open();
            System.Data.DataTable tbClient;
            tbClient = new System.Data.DataTable("Client");
            adapt.Fill(tbClient);
            Client Client;
            Client = new Client();
            if (tbClient.Rows.Count > 0) {
                System.Data.DataRow rowClient;
                rowClient = tbClient.Rows[0];
                Client.ClientName = System.Convert.ToString(rowClient["ClientName"]);
                Client.Description = System.Convert.ToString(rowClient["Description"]);
                Client.CompanyID = System.Convert.ToInt32(rowClient["CompanyID"]);
                return Client;
            }
            else {
                return null;
            }
        }
    }
//}
