//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clscover {

        public static void Insert(Cover cover)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Cover", conn);
            conn.Open();
            System.Data.DataTable tbCover;
            tbCover = new System.Data.DataTable("Cover");
            adapt.Fill(tbCover);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
          //  adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
           
                System.Data.DataRow rowCover;
                rowCover = tbCover.NewRow();             
                rowCover["CoverTitle"] = cover.CoverTitle;
                rowCover["CoverPage"] = cover.CoverPage;
                rowCover["CoverFileName"] = cover.CoverFileName;
                rowCover["CreatedBy"] = cover.CreatedBy;
                rowCover["CreatedDate"] = cover.CreatedDate;
                rowCover["ModifiedBy"] = cover.ModifiedBy;
                rowCover["ModifiedDate"] = cover.ModifiedDate;
                tbCover.Rows.Add(rowCover);
                adapt.Update(tbCover);
      
        }

        public static void Update(Cover cover) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Company where  CoverID = " + cover.CoverID + "", conn);       
            conn.Open();
            System.Data.DataTable tbCover;
            tbCover = new System.Data.DataTable("Cover");
            adapt.Fill(tbCover);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbCover.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowCover;
                rowCover = tbCover.Rows[0];
                rowCover["CoverID"] = cover.CoverID;
                rowCover["CoverTitle"] = cover.CoverTitle;
                rowCover["CoverPage"] = cover.CoverPage;
                rowCover["CoverFileName"] = cover.CoverFileName;
                rowCover["CreatedBy"] = cover.CreatedBy;
                rowCover["CreatedDate"] = cover.CreatedDate;
                rowCover["ModifiedBy"] = cover.ModifiedBy;
                rowCover["ModifiedDate"] = cover.ModifiedDate;
                adapt.Update(tbCover);
            }
            else {
                System.Data.DataRow rowCover;
                rowCover = tbCover.NewRow();
                rowCover["CoverID"] = cover.CoverID;
                rowCover["CoverTitle"] = cover.CoverTitle;
                rowCover["CoverPage"] = cover.CoverPage;
                rowCover["CoverFileName"] = cover.CoverFileName;
                rowCover["CreatedBy"] = cover.CreatedBy;
                rowCover["CreatedDate"] = cover.CreatedDate;
                rowCover["ModifiedBy"] = cover.ModifiedBy;
                rowCover["ModifiedDate"] = cover.ModifiedDate;
                tbCover.Rows.Add(rowCover);
                adapt.Update(tbCover);
            }
        }

        public static Cover getCover(Int32 CoverID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;

            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Cover where  CoverID = " + CoverID + "", conn);
            
            conn.Open();
            System.Data.DataTable tbCover;
            tbCover = new System.Data.DataTable("Cover");
            adapt.Fill(tbCover);
            Cover Cover;
            Cover = new Cover();
            if (tbCover.Rows.Count > 0) {
                System.Data.DataRow rowCover;
                rowCover = tbCover.Rows[0];
                Cover.CoverID = System.Convert.ToInt32(rowCover["CoverID"]);
                Cover.CoverTitle = System.Convert.ToString(rowCover["CoverTitle"]);
                Cover.CoverPage = System.Convert.ToString(rowCover["CoverPage"]);
                Cover.CoverFileName = System.Convert.ToString(rowCover["CoverFileName"]);
                Cover.CreatedBy = System.Convert.ToString(rowCover["CreatedBy"]);
                Cover.CreatedDate = System.Convert.ToDateTime(rowCover["CreatedDate"]);
                Cover.ModifiedBy = System.Convert.ToString(rowCover["ModifiedBy"]);
                Cover.ModifiedDate = System.Convert.ToDateTime(rowCover["ModifiedDate"]);
                Cover.PresentationID = System.Convert.ToInt32(rowCover["PresentationID"]);
                return Cover;
            }
            else {
                return null;
            }
        }
   
    }

