//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsDirectory {



        public static Directorytbl getDirectory(Int32 DirectoryID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;

            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Directory where  DirectoryID = " + DirectoryID + "", conn);


            conn.Open();
            System.Data.DataTable tbDirectory;
            tbDirectory = new System.Data.DataTable("Directory");
            adapt.Fill(tbDirectory);
            Directorytbl Directorytbl;
            Directorytbl = new Directorytbl();
            if (tbDirectory.Rows.Count > 0)
            {
                System.Data.DataRow rowDirectory;
                rowDirectory = tbDirectory.Rows[0];
                Directorytbl.DirectoryID = System.Convert.ToInt32(rowDirectory["DirectoryID"]);
                Directorytbl.DirectoryTitle = System.Convert.ToString(rowDirectory["DirectoryTitle"]);
                Directorytbl.DirectoryPage = System.Convert.ToString(rowDirectory["DirectoryPage"]);
                Directorytbl.DirectoryFileName = System.Convert.ToString(rowDirectory["DirectoryFileName"]);
                Directorytbl.CreatedBy = System.Convert.ToString(rowDirectory["CreatedBy"]);
                Directorytbl.CreatedDate = System.Convert.ToDateTime(rowDirectory["CreatedDate"]);
                Directorytbl.ModifiedBy = System.Convert.ToString(rowDirectory["ModifiedBy"]);
                Directorytbl.ModifiedDate = System.Convert.ToDateTime(rowDirectory["ModifiedDate"]);
                Directorytbl.PresentationID = System.Convert.ToInt32(rowDirectory["PresentationID"]);
                return Directorytbl;
            }
            else {
                return null;
            }
        }
    }

