//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsproject {

        public static void Insert(Project project)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Project", conn);
            conn.Open();
            System.Data.DataTable tbProject;
            tbProject = new System.Data.DataTable("Project");
            adapt.Fill(tbProject);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
           
                System.Data.DataRow rowProject;
                rowProject = tbProject.NewRow();
                //rowProject["ProjectID"] = project.ProjectID;
                rowProject["ProjectName"] = project.ProjectName;
                rowProject["Description"] = project.Description;
                rowProject["ClientID"] = project.ClientID;
                tbProject.Rows.Add(rowProject);
                adapt.Update(tbProject);
            
        }
        public static void Update(Project project) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Project where  ProjectID = " + project.ProjectID + "", conn);
            conn.Open();
            System.Data.DataTable tbProject;
            tbProject = new System.Data.DataTable("Project");
            adapt.Fill(tbProject);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbProject.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowProject;
                rowProject = tbProject.Rows[0];
                rowProject["ProjectName"] = project.ProjectName;
                rowProject["Description"] = project.Description;
                rowProject["ClientID"] = project.ClientID;
                adapt.Update(tbProject);
            }
            else {
                System.Data.DataRow rowProject;
                rowProject = tbProject.NewRow();
                rowProject["ProjectID"] = project.ProjectID;
                rowProject["ProjectName"] = project.ProjectName;
                rowProject["Description"] = project.Description;
                rowProject["ClientID"] = project.ClientID;
                tbProject.Rows.Add(rowProject);
                adapt.Update(tbProject);
            }
        }
        
        public static Project getProject(Int32 ProjectID) 
        {           
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Project where  ProjectID = " + ProjectID + "", conn);            
            
            conn.Open();
            System.Data.DataTable tbProject;
            tbProject = new System.Data.DataTable("Project");
            adapt.Fill(tbProject);
            Project Project;

            Project = new Project();

            if (tbProject.Rows.Count > 0) {
                System.Data.DataRow rowProject;
                rowProject = tbProject.Rows[0];
                Project.ProjectName = System.Convert.ToString(rowProject["ProjectName"]);
                Project.Description = System.Convert.ToString(rowProject["Description"]);
                Project.ClientID = System.Convert.ToInt32(rowProject["ClientID"]);
                return Project;
            }
            else {
                return null;
            }
        }
    }
//}
