//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsproduction {
        public static void Insert(Production production)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Production", conn);
            conn.Open();
            System.Data.DataTable tbProduction;
            tbProduction = new System.Data.DataTable("Production");
            adapt.Fill(tbProduction);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);

            adapt.InsertCommand = mybuild.GetInsertCommand();
          
      
                System.Data.DataRow rowProduction;
                rowProduction = tbProduction.NewRow();
                rowProduction["ProductionID"] = production.ProductionID;
                rowProduction["ImageFile"] = production.ImageFile;
                rowProduction["ImagePath"] = production.ImagePath;
                rowProduction["VoiceOver"] = production.VoiceOver;
                rowProduction["Description"] = production.Description;
                rowProduction["Rank"] = production.Rank;
                rowProduction["CreatedBy"] = production.CreatedBy;
                rowProduction["CreatedDate"] = production.CreatedDate;
                rowProduction["ModifiedBy"] = production.ModifiedBy;
                rowProduction["ModifiedDate"] = production.ModifiedDate;
                rowProduction["PresentationID"] = production.PresentationID;
                tbProduction.Rows.Add(rowProduction);
                adapt.Update(tbProduction);
     
        }
        public static void Update(Production production) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
 
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Production where  ProductionID = " + production.ProductionID + "", conn);
            conn.Open();
            System.Data.DataTable tbProduction;
            tbProduction = new System.Data.DataTable("Production");
            adapt.Fill(tbProduction);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
         
           
                // Edit methods
                System.Data.DataRow rowProduction;
                rowProduction = tbProduction.Rows[0];
                rowProduction["ProductionID"] = production.ProductionID;
                rowProduction["ImageFile"] = production.ImageFile;
                rowProduction["ImagePath"] = production.ImagePath;
                rowProduction["VoiceOver"] = production.VoiceOver;
                rowProduction["Description"] = production.Description;
                rowProduction["Rank"] = production.Rank;
                rowProduction["CreatedBy"] = production.CreatedBy;
                rowProduction["CreatedDate"] = production.CreatedDate;
                rowProduction["ModifiedBy"] = production.ModifiedBy;
                rowProduction["ModifiedDate"] = production.ModifiedDate;
                rowProduction["PresentationID"] = production.PresentationID;
                adapt.Update(tbProduction);
           
        }

        public static Production getProduction(Int32 ProductionID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
        

            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Production where  ProductionID = " + ProductionID + "", conn);
            conn.Open();
            System.Data.DataTable tbProduction;
            tbProduction = new System.Data.DataTable("Production");
            adapt.Fill(tbProduction);
            Production Production;
            Production = new Production();
            if (tbProduction.Rows.Count > 0) {
                System.Data.DataRow rowProduction;
                rowProduction = tbProduction.Rows[0];
                Production.ProductionID = System.Convert.ToInt32(rowProduction["ProductionID"]);
                Production.ImageFile = System.Convert.ToString(rowProduction["ImageFile"]);
                Production.ImagePath = System.Convert.ToString(rowProduction["ImagePath"]);

                Production.ImageFile2 = System.Convert.ToString(rowProduction["ImageFile2"]);
                Production.ImagePath2 = System.Convert.ToString(rowProduction["ImagePath2"]);

                Production.ImageFile3 = System.Convert.ToString(rowProduction["ImageFile3"]);
                Production.ImagePath2 = System.Convert.ToString(rowProduction["ImagePath3"]);


                Production.VoiceOver = System.Convert.ToString(rowProduction["VoiceOver"]);
                Production.Description = System.Convert.ToString(rowProduction["Description"]);
                Production.Rank = System.Convert.ToInt32(rowProduction["Rank"]);
                Production.CreatedBy = System.Convert.ToString(rowProduction["CreatedBy"]);
                Production.CreatedDate = System.Convert.ToDateTime(rowProduction["CreatedDate"]);
                Production.ModifiedBy = System.Convert.ToString(rowProduction["ModifiedBy"]);
                Production.ModifiedDate = System.Convert.ToDateTime(rowProduction["ModifiedDate"]);
                Production.PresentationID = System.Convert.ToInt32(rowProduction["PresentationID"]);
                Production.TemplateID = System.Convert.ToInt32(rowProduction["TemplateID"]);

                Production.Title1 = System.Convert.ToString(rowProduction["Title1"]);
                Production.Title2 = System.Convert.ToString(rowProduction["Title2"]);
                return Production;
            }
            else {
                return null;
            }
        }
    }
