//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clspage {

        public static void Insert(Page page)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Page", conn);
            conn.Open();
            System.Data.DataTable tbPage;
            tbPage = new System.Data.DataTable("Page");
            adapt.Fill(tbPage);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            //adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
      
                System.Data.DataRow rowPage;
                rowPage = tbPage.NewRow();
                //rowPage["PageID"] = page.PageID;
                rowPage["PageName"] = page.PageName;
                rowPage["PageContent"] = page.PageContent;
                rowPage["Ordinal"] = page.Ordinal;
                rowPage["PresentationID"] = page.PresentationID;
                tbPage.Rows.Add(rowPage);
                adapt.Update(tbPage);
     
        }
        public static void Update(Page page) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Page where PageID= " + page.PageID + "", conn);
            conn.Open();
            System.Data.DataTable tbPage;
            tbPage = new System.Data.DataTable("Page");
            adapt.Fill(tbPage);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbPage.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowPage;
                rowPage = tbPage.Rows[0];
                rowPage["PageID"] = page.PageID;
                rowPage["PageName"] = page.PageName;
                rowPage["PageContent"] = page.PageContent;
                rowPage["Ordinal"] = page.Ordinal;
                rowPage["PresentationID"] = page.PresentationID;
                adapt.Update(tbPage);
            }
            else {
                System.Data.DataRow rowPage;
                rowPage = tbPage.NewRow();
                rowPage["PageID"] = page.PageID;
                rowPage["PageName"] = page.PageName;
                rowPage["PageContent"] = page.PageContent;
                rowPage["Ordinal"] = page.Ordinal;
                rowPage["PresentationID"] = page.PresentationID;
                tbPage.Rows.Add(rowPage);
                adapt.Update(tbPage);
            }
        }

        public static Page getPage(Int32 PageID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Page where  PageID = " + PageID + "", conn);
            conn.Open();
            System.Data.DataTable tbPage;
            tbPage = new System.Data.DataTable("Page");
            adapt.Fill(tbPage);
            Page Page;
            Page = new Page();
            if (tbPage.Rows.Count > 0) {
                System.Data.DataRow rowPage;
                rowPage = tbPage.Rows[0];
               // Page.PageID = System.Convert.ToInt32(rowPage["PageID"]);
                Page.PageName = System.Convert.ToString(rowPage["PageName"]);
                Page.PageContent = System.Convert.ToString(rowPage["PageContent"]);
                Page.Ordinal = System.Convert.ToInt32(rowPage["Ordinal"]);
                Page.PresentationID = System.Convert.ToInt32(rowPage["PresentationID"]);
                return Page;
            }
            else {
                return null;
            }
        }
    }
//}
