//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clssound {
        
        public static void Update(Sound sound) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Sound where 1=1", conn);
            conn.Open();
            System.Data.DataTable tbSound;
            tbSound = new System.Data.DataTable("Sound");
            adapt.Fill(tbSound);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbSound.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowSound;
                rowSound = tbSound.Rows[0];
                rowSound["SoundID"] = sound.SoundID;
                rowSound["SoundFile"] = sound.SoundFile;
                rowSound["SoundPath"] = sound.SoundPath;
                rowSound["CreatedBy"] = sound.CreatedBy;
                rowSound["CreatedDate"] = sound.CreatedDate;
                rowSound["ModifiedBy"] = sound.ModifiedBy;
                rowSound["ModifiedDate"] = sound.ModifiedDate;
                rowSound["PresentationID"] = sound.PresentationID;
                adapt.Update(tbSound);
            }
            else {
                System.Data.DataRow rowSound;
                rowSound = tbSound.NewRow();
                rowSound["SoundID"] = sound.SoundID;
                rowSound["SoundFile"] = sound.SoundFile;
                rowSound["SoundPath"] = sound.SoundPath;
                rowSound["CreatedBy"] = sound.CreatedBy;
                rowSound["CreatedDate"] = sound.CreatedDate;
                rowSound["ModifiedBy"] = sound.ModifiedBy;
                rowSound["ModifiedDate"] = sound.ModifiedDate;
                rowSound["PresentationID"] = sound.PresentationID;
                tbSound.Rows.Add(rowSound);
                adapt.Update(tbSound);
            }
        }

        public static Sound getSound(Int32 SoundID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
        
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Sound where  SoundID = " + SoundID + "", conn);
            conn.Open();
            System.Data.DataTable tbSound;
            tbSound = new System.Data.DataTable("Sound");
            adapt.Fill(tbSound);
            Sound Sound;
            Sound = new Sound();
            if (tbSound.Rows.Count > 0) {
                System.Data.DataRow rowSound;
                rowSound = tbSound.Rows[0];
                Sound.SoundID = System.Convert.ToInt32(rowSound["SoundID"]);
                Sound.SoundFile = System.Convert.ToString(rowSound["SoundFile"]);
                Sound.SoundPath = System.Convert.ToString(rowSound["SoundPath"]);
                Sound.CreatedBy = System.Convert.ToString(rowSound["CreatedBy"]);
                Sound.CreatedDate = System.Convert.ToDateTime(rowSound["CreatedDate"]);
                Sound.ModifiedBy = System.Convert.ToString(rowSound["ModifiedBy"]);
                Sound.ModifiedDate = System.Convert.ToDateTime(rowSound["ModifiedDate"]);
                Sound.PresentationID = System.Convert.ToInt32(rowSound["PresentationID"]);
                return Sound;
            }
            else {
                return null;
            }
        }
    }

