//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clstargetMarket {
        
        public static void Update(TargetMarket targetMarket) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TargetMarket where 1=1", conn);
            conn.Open();
            System.Data.DataTable tbTargetMarket;
            tbTargetMarket = new System.Data.DataTable("TargetMarket");
            adapt.Fill(tbTargetMarket);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbTargetMarket.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowTargetMarket;
                rowTargetMarket = tbTargetMarket.Rows[0];
                rowTargetMarket["TargetMarketID"] = targetMarket.TargetMarketID;
                rowTargetMarket["TargetMarketTitle"] = targetMarket.TargetMarketTitle;
                rowTargetMarket["TargetMarketPage"] = targetMarket.TargetMarketPage;
                rowTargetMarket["TargetMarketFileName"] = targetMarket.TargetMarketFileName;
                rowTargetMarket["CreatedBy"] = targetMarket.CreatedBy;
                rowTargetMarket["CreatedDate"] = targetMarket.CreatedDate;
                rowTargetMarket["ModifiedBy"] = targetMarket.ModifiedBy;
                rowTargetMarket["ModifiedDate"] = targetMarket.ModifiedDate;
                rowTargetMarket["PresentationID"] = targetMarket.PresentationID;
                adapt.Update(tbTargetMarket);
            }
            else {
                System.Data.DataRow rowTargetMarket;
                rowTargetMarket = tbTargetMarket.NewRow();
                rowTargetMarket["TargetMarketID"] = targetMarket.TargetMarketID;
                rowTargetMarket["TargetMarketTitle"] = targetMarket.TargetMarketTitle;
                rowTargetMarket["TargetMarketPage"] = targetMarket.TargetMarketPage;
                rowTargetMarket["TargetMarketFileName"] = targetMarket.TargetMarketFileName;
                rowTargetMarket["CreatedBy"] = targetMarket.CreatedBy;
                rowTargetMarket["CreatedDate"] = targetMarket.CreatedDate;
                rowTargetMarket["ModifiedBy"] = targetMarket.ModifiedBy;
                rowTargetMarket["ModifiedDate"] = targetMarket.ModifiedDate;
                rowTargetMarket["PresentationID"] = targetMarket.PresentationID;
                tbTargetMarket.Rows.Add(rowTargetMarket);
                adapt.Update(tbTargetMarket);
            }
        }

        public static TargetMarket getTargetMarket(Int32 TargetMarketID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
           
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TargetMarket where  TargetMarketID = " + TargetMarketID + "", conn);
            conn.Open();
            System.Data.DataTable tbTargetMarket;
            tbTargetMarket = new System.Data.DataTable("TargetMarket");
            adapt.Fill(tbTargetMarket);
            TargetMarket TargetMarket;
            TargetMarket = new TargetMarket();
            if (tbTargetMarket.Rows.Count > 0) {
                System.Data.DataRow rowTargetMarket;
                rowTargetMarket = tbTargetMarket.Rows[0];
                TargetMarket.TargetMarketID = System.Convert.ToInt32(rowTargetMarket["TargetMarketID"]);
                TargetMarket.TargetMarketTitle = System.Convert.ToString(rowTargetMarket["TargetMarketTitle"]);
                TargetMarket.TargetMarketPage = System.Convert.ToString(rowTargetMarket["TargetMarketPage"]);
                TargetMarket.TargetMarketFileName = System.Convert.ToString(rowTargetMarket["TargetMarketFileName"]);
                TargetMarket.CreatedBy = System.Convert.ToString(rowTargetMarket["CreatedBy"]);
                TargetMarket.CreatedDate = System.Convert.ToDateTime(rowTargetMarket["CreatedDate"]);
                TargetMarket.ModifiedBy = System.Convert.ToString(rowTargetMarket["ModifiedBy"]);
                TargetMarket.ModifiedDate = System.Convert.ToDateTime(rowTargetMarket["ModifiedDate"]);
                TargetMarket.PresentationID = System.Convert.ToInt32(rowTargetMarket["PresentationID"]);
                return TargetMarket;
            }
            else {
                return null;
            }
        }
    }

