//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clstimeTable {

        public static void Insert(TimeTableclass timeTable)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TimeTable", conn);
            conn.Open();
            System.Data.DataTable tbTimeTable;
            tbTimeTable = new System.Data.DataTable("TimeTable");
            adapt.Fill(tbTimeTable);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
       
            adapt.InsertCommand = mybuild.GetInsertCommand();
        
                System.Data.DataRow rowTimeTable;
                rowTimeTable = tbTimeTable.NewRow();
                //rowTimeTable["TimeTableID"] = timeTable.TimeTableID;
                //rowTimeTable["TimeTableTitle"] = timeTable.TimeTableTitle;
                //rowTimeTable["TimeTablePage"] = timeTable.TimeTablePage;
                //rowTimeTable["TimeTableFileName"] = timeTable.TimeTableFileName;
                //rowTimeTable["CreatedBy"] = timeTable.CreatedBy;
                //rowTimeTable["CreatedDate"] = timeTable.CreatedDate;
                //rowTimeTable["ModifiedBy"] = timeTable.ModifiedBy;
                //rowTimeTable["ModifiedDate"] = timeTable.ModifiedDate;
                rowTimeTable["PresentationID"] = timeTable.PresentationID;
                rowTimeTable["TRow"] = timeTable.TRow;
                rowTimeTable["TCol"] = timeTable.TCol;
                tbTimeTable.Rows.Add(rowTimeTable);
                adapt.Update(tbTimeTable);
          
        }
        public static void Update(TimeTableclass timeTable)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;        
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TimeTable where TimeTableID= " + timeTable.TimeTableID + "", conn);
            conn.Open();
            System.Data.DataTable tbTimeTable;
            tbTimeTable = new System.Data.DataTable("TimeTable");
            adapt.Fill(tbTimeTable);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
         
                // Edit methods
                System.Data.DataRow rowTimeTable;
                rowTimeTable = tbTimeTable.Rows[0];
                rowTimeTable["TimeTableID"] = timeTable.TimeTableID;
                rowTimeTable["TimeTableTitle"] = timeTable.TimeTableTitle;
                rowTimeTable["TimeTablePage"] = timeTable.TimeTablePage;
                //rowTimeTable["TimeTableFileName"] = timeTable.TimeTableFileName;
                //rowTimeTable["CreatedBy"] = timeTable.CreatedBy;
                //rowTimeTable["CreatedDate"] = timeTable.CreatedDate;
                //rowTimeTable["ModifiedBy"] = timeTable.ModifiedBy;
                //rowTimeTable["ModifiedDate"] = timeTable.ModifiedDate;
                //rowTimeTable["PresentationID"] = timeTable.PresentationID;
                rowTimeTable["TRow"] = timeTable.TRow;
                rowTimeTable["TCol"] = timeTable.TCol;
                adapt.Update(tbTimeTable);
         
        }
        public static TimeTableclass getTimeTable(Int32 TimeTableID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
       
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TimeTable where  TimeTableID = " + TimeTableID + "", conn);
            conn.Open();
            System.Data.DataTable tbTimeTable;
            tbTimeTable = new System.Data.DataTable("TimeTable");
            adapt.Fill(tbTimeTable);
            TimeTableclass TimeTable;
            TimeTable = new TimeTableclass();
            if (tbTimeTable.Rows.Count > 0) {
                System.Data.DataRow rowTimeTable;
                rowTimeTable = tbTimeTable.Rows[0];
                TimeTable.TimeTableID = System.Convert.ToInt32(rowTimeTable["TimeTableID"]);
                TimeTable.TimeTableTitle = System.Convert.ToString(rowTimeTable["TimeTableTitle"]);
                TimeTable.TimeTablePage = System.Convert.ToString(rowTimeTable["TimeTablePage"]);
                TimeTable.TimeTableFileName = System.Convert.ToString(rowTimeTable["TimeTableFileName"]);
                //TimeTable.CreatedBy = System.Convert.ToString(rowTimeTable["CreatedBy"]);
                //TimeTable.CreatedDate = System.Convert.ToDateTime(rowTimeTable["CreatedDate"]);
                //TimeTable.ModifiedBy = System.Convert.ToString(rowTimeTable["ModifiedBy"]);
                //TimeTable.ModifiedDate = System.Convert.ToDateTime(rowTimeTable["ModifiedDate"]);
                TimeTable.PresentationID = System.Convert.ToInt32(rowTimeTable["PresentationID"]);
                TimeTable.TRow = System.Convert.ToInt32(rowTimeTable["TRow"]);
                TimeTable.TCol = System.Convert.ToInt32(rowTimeTable["TCol"]);
                return TimeTable;
            }
            else {
                return null;
            }
        }
    }

