//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clsterribleUsers {
        
        public static void Update(TerribleUsers terribleUsers) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TerribleUsers where TUserID =" + terribleUsers.TUserID + "", conn);

            
            conn.Open();
            System.Data.DataTable tbTerribleUsers;
            tbTerribleUsers = new System.Data.DataTable("TerribleUsers");
            adapt.Fill(tbTerribleUsers);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbTerribleUsers.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowTerribleUsers;
                rowTerribleUsers = tbTerribleUsers.Rows[0];
                rowTerribleUsers["TUserID"] = terribleUsers.TUserID;
                rowTerribleUsers["TUserName"] = terribleUsers.TUserName;
                rowTerribleUsers["TPassword"] = terribleUsers.TPassword;
                rowTerribleUsers["TFirstName"] = terribleUsers.TFirstName;
                rowTerribleUsers["TLastName"] = terribleUsers.TLastName;
                rowTerribleUsers["TRoleID"] = terribleUsers.TRoleID;
                adapt.Update(tbTerribleUsers);
            }
            else {
                System.Data.DataRow rowTerribleUsers;
                rowTerribleUsers = tbTerribleUsers.NewRow();
                rowTerribleUsers["TUserID"] = terribleUsers.TUserID;
                rowTerribleUsers["TUserName"] = terribleUsers.TUserName;
                rowTerribleUsers["TPassword"] = terribleUsers.TPassword;
                rowTerribleUsers["TFirstName"] = terribleUsers.TFirstName;
                rowTerribleUsers["TLastName"] = terribleUsers.TLastName;
                rowTerribleUsers["TRoleID"] = terribleUsers.TRoleID;
                tbTerribleUsers.Rows.Add(rowTerribleUsers);
                adapt.Update(tbTerribleUsers);
            }
        }

        public static void Insert(TerribleUsers terribleUsers)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TerribleUsers", conn);


            conn.Open();
            System.Data.DataTable tbTerribleUsers;
            tbTerribleUsers = new System.Data.DataTable("TerribleUsers");
            adapt.Fill(tbTerribleUsers);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
          
            adapt.InsertCommand = mybuild.GetInsertCommand();
           
                System.Data.DataRow rowTerribleUsers;
                rowTerribleUsers = tbTerribleUsers.NewRow();
                //rowTerribleUsers["TUserID"] = terribleUsers.TUserID;
                rowTerribleUsers["TUserName"] = terribleUsers.TUserName;
                rowTerribleUsers["TPassword"] = terribleUsers.TPassword;
                rowTerribleUsers["TFirstName"] = terribleUsers.TFirstName;
                rowTerribleUsers["TLastName"] = terribleUsers.TLastName;
                rowTerribleUsers["TRoleID"] = terribleUsers.TRoleID;
                tbTerribleUsers.Rows.Add(rowTerribleUsers);
                adapt.Update(tbTerribleUsers);
          
        }

        public static TerribleUsers getTerribleUsers(Int32 TUserID)
        {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from TerribleUsers where TUserID = " + TUserID + "", conn);
         
            conn.Open();
            System.Data.DataTable tbTerribleUsers;
            tbTerribleUsers = new System.Data.DataTable("TerribleUsers");
            adapt.Fill(tbTerribleUsers);
            TerribleUsers TerribleUsers;
            TerribleUsers = new TerribleUsers();
            if (tbTerribleUsers.Rows.Count > 0) {
                System.Data.DataRow rowTerribleUsers;
                rowTerribleUsers = tbTerribleUsers.Rows[0];
                TerribleUsers.TUserID = System.Convert.ToInt32(rowTerribleUsers["TUserID"]);
                TerribleUsers.TUserName = System.Convert.ToString(rowTerribleUsers["TUserName"]);
                TerribleUsers.TPassword = System.Convert.ToString(rowTerribleUsers["TPassword"]);
                TerribleUsers.TFirstName = System.Convert.ToString(rowTerribleUsers["TFirstName"]);
                TerribleUsers.TLastName = System.Convert.ToString(rowTerribleUsers["TLastName"]);
                TerribleUsers.TRoleID = System.Convert.ToInt32(rowTerribleUsers["TRoleID"]);
                return TerribleUsers;
            }
            else {
                return null;
            }
        }
    }

