//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Linq;
    
    
    public class clstemplate {
        
        public static void Update(Template template) {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Template where 1=1", conn);
            conn.Open();
            System.Data.DataTable tbTemplate;
            tbTemplate = new System.Data.DataTable("Template");
            adapt.Fill(tbTemplate);
            SqlCommandBuilder mybuild;
            mybuild = new System.Data.SqlClient.SqlCommandBuilder(adapt);
            adapt.UpdateCommand = mybuild.GetUpdateCommand();
            adapt.InsertCommand = mybuild.GetInsertCommand();
            if (tbTemplate.Rows.Count > 0) {
                // Edit methods
                System.Data.DataRow rowTemplate;
                rowTemplate = tbTemplate.Rows[0];
                rowTemplate["TemplateID"] = template.TemplateID;
                rowTemplate["Title"] = template.Title;
                rowTemplate["PageContent"] = template.PageContent;
                rowTemplate["Ordinal"] = template.Ordinal;
                rowTemplate["PresentationID"] = template.PresentationID;
                adapt.Update(tbTemplate);
            }
            else {
                System.Data.DataRow rowTemplate;
                rowTemplate = tbTemplate.NewRow();
                rowTemplate["TemplateID"] = template.TemplateID;
                rowTemplate["Title"] = template.Title;
                rowTemplate["PageContent"] = template.PageContent;
                rowTemplate["Ordinal"] = template.Ordinal;
                rowTemplate["PresentationID"] = template.PresentationID;
                tbTemplate.Rows.Add(rowTemplate);
                adapt.Update(tbTemplate);
            }
        }
        
        public static Template getTemplate() {
            SqlConnection conn;
            conn = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["terrible1ConnectionString"].ConnectionString);
            SqlDataAdapter adapt;
            adapt = new System.Data.SqlClient.SqlDataAdapter("select * from Template where 1=1", conn);
            conn.Open();
            System.Data.DataTable tbTemplate;
            tbTemplate = new System.Data.DataTable("Template");
            adapt.Fill(tbTemplate);
            Template Template;
            Template = new Template();
            if (tbTemplate.Rows.Count > 0) {
                System.Data.DataRow rowTemplate;
                rowTemplate = tbTemplate.Rows[0];
                Template.TemplateID = System.Convert.ToInt32(rowTemplate["TemplateID"]);
                Template.Title = System.Convert.ToString(rowTemplate["Title"]);
                Template.PageContent = System.Convert.ToString(rowTemplate["PageContent"]);
                Template.Ordinal = System.Convert.ToInt32(rowTemplate["Ordinal"]);
                Template.PresentationID = System.Convert.ToInt32(rowTemplate["PresentationID"]);
                return Template;
            }
            else {
                return null;
            }
        }
    }
