//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Company {
        
        private object _CompanyID;
        
        private object _CompanyName;
        
        private object _Description;
        private object _Logo;
        
        public Company() {
        }
        
        public virtual object CompanyID {
            get {
                return this._CompanyID;
            }
            set {
                this._CompanyID = value;
            }
        }
        
        public virtual object CompanyName {
            get {
                return this._CompanyName;
            }
            set {
                this._CompanyName = value;
            }
        }
        
        public virtual object Description {
            get {
                return this._Description;
            }
            set {
                this._Description = value;
            }
        }
        public virtual object Logo
        {
            get
            {
                return this._Logo;
            }
            set
            {
                this._Logo = value;
            }
        }
    }
    
    public class CompanyCollection : System.Collections.CollectionBase {
        
        public virtual Company this[int index] {
            get {
                return ((Company)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Company Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Company Item) {
            List.Remove(Item);
        }
    }

