//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Cover {
        
        private object _CoverID;
        
        private object _CoverTitle;
        
        private object _CoverPage;
        
        private object _CoverFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;

        private object _PresentationID;
        
        public Cover() {
        }
        
        public virtual object CoverID {
            get {
                return this._CoverID;
            }
            set {
                this._CoverID = value;
            }
        }
        public virtual object PresentationID
        {
            get
            {
                return this._PresentationID;
            }
            set
            {
                this._PresentationID = value;
            }
        }
        
        public virtual object CoverTitle {
            get {
                return this._CoverTitle;
            }
            set {
                this._CoverTitle = value;
            }
        }
        
        public virtual object CoverPage {
            get {
                return this._CoverPage;
            }
            set {
                this._CoverPage = value;
            }
        }
        
        public virtual object CoverFileName {
            get {
                return this._CoverFileName;
            }
            set {
                this._CoverFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
    }
    
    public class CoverCollection : System.Collections.CollectionBase {
        
        public virtual Cover this[int index] {
            get {
                return ((Cover)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Cover Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Cover Item) {
            List.Remove(Item);
        }
    }


