//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class DirectorsVideos {
        
        private object _VideoID;
        
        private object _VideoTitle;
        
        private object _VideoFile;
        
        private object _VideoPath;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _BoardID;
        
        private object _Rank;
        
        public DirectorsVideos() {
        }
        
        public virtual object VideoID {
            get {
                return this._VideoID;
            }
            set {
                this._VideoID = value;
            }
        }
        
        public virtual object VideoTitle {
            get {
                return this._VideoTitle;
            }
            set {
                this._VideoTitle = value;
            }
        }
        
        public virtual object VideoFile {
            get {
                return this._VideoFile;
            }
            set {
                this._VideoFile = value;
            }
        }
        
        public virtual object VideoPath {
            get {
                return this._VideoPath;
            }
            set {
                this._VideoPath = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object BoardID {
            get {
                return this._BoardID;
            }
            set {
                this._BoardID = value;
            }
        }
        
        public virtual object Rank {
            get {
                return this._Rank;
            }
            set {
                this._Rank = value;
            }
        }
    }
    
    public class DirectorsVideosCollection : System.Collections.CollectionBase {
        
        public virtual DirectorsVideos this[int index] {
            get {
                return ((DirectorsVideos)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(DirectorsVideos Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(DirectorsVideos Item) {
            List.Remove(Item);
        }
    }

