//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class DirectorsBoard {
        
        private object _BoardID;
        
        private object _BoardTitle;
        
        private object _BoardPage;
        
        private object _BoardFileName;

        private object _BoardDescription;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;
        
        public DirectorsBoard() {
        }
        
        public virtual object BoardID {
            get {
                return this._BoardID;
            }
            set {
                this._BoardID = value;
            }
        }
        
        public virtual object BoardTitle {
            get {
                return this._BoardTitle;
            }
            set {
                this._BoardTitle = value;
            }
        }
        
        public virtual object BoardPage {
            get {
                return this._BoardPage;
            }
            set {
                this._BoardPage = value;
            }
        }
        
        public virtual object BoardFileName {
            get {
                return this._BoardFileName;
            }
            set {
                this._BoardFileName = value;
            }
        }
        public virtual object BoardDescription
        {
            get
            {
                return this._BoardDescription;
            }
            set
            {
                this._BoardDescription = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class DirectorsBoardCollection : System.Collections.CollectionBase {
        
        public virtual DirectorsBoard this[int index] {
            get {
                return ((DirectorsBoard)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(DirectorsBoard Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(DirectorsBoard Item) {
            List.Remove(Item);
        }
    }

