//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Directorytbl {
        
        private object _DirectoryID;
        
        private object _DirectoryTitle;
        
        private object _DirectoryPage;
        
        private object _DirectoryFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;

        public Directorytbl()
        {
        }
        
        public virtual object DirectoryID {
            get {
                return this._DirectoryID;
            }
            set {
                this._DirectoryID = value;
            }
        }
        
        public virtual object DirectoryTitle {
            get {
                return this._DirectoryTitle;
            }
            set {
                this._DirectoryTitle = value;
            }
        }
        
        public virtual object DirectoryPage {
            get {
                return this._DirectoryPage;
            }
            set {
                this._DirectoryPage = value;
            }
        }
        
        public virtual object DirectoryFileName {
            get {
                return this._DirectoryFileName;
            }
            set {
                this._DirectoryFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }

    public class DirectorytblCollection : System.Collections.CollectionBase
    {

        public virtual Directorytbl this[int index]
        {
            get {
                return ((Directorytbl)(List[index]));
            }
            set {
                List[index] = value;
            }
        }

        public virtual void Add(Directorytbl Item)
        {
            List.Add(Item);
        }

        public virtual void Remove(Directorytbl Item)
        {
            List.Remove(Item);
        }
    }

