//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Documents {
        
        private object _DocumentID;
        
        private object _DocumentTitle;
        
        private object _DocumentPath;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        public Documents() {
        }
        
        public virtual object DocumentID {
            get {
                return this._DocumentID;
            }
            set {
                this._DocumentID = value;
            }
        }
        
        public virtual object DocumentTitle {
            get {
                return this._DocumentTitle;
            }
            set {
                this._DocumentTitle = value;
            }
        }
        
        public virtual object DocumentPath {
            get {
                return this._DocumentPath;
            }
            set {
                this._DocumentPath = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
    }
    
    public class DocumentsCollection : System.Collections.CollectionBase {
        
        public virtual Documents this[int index] {
            get {
                return ((Documents)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Documents Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Documents Item) {
            List.Remove(Item);
        }
    }

