//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class ModeTone {
        
        private object _ModeToneID;
        
        private object _ModeToneTitle;
        
        private object _ModeTonePage;
        
        private object _ModeToneFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;
        
        public ModeTone() {
        }
        
        public virtual object ModeToneID {
            get {
                return this._ModeToneID;
            }
            set {
                this._ModeToneID = value;
            }
        }
        
        public virtual object ModeToneTitle {
            get {
                return this._ModeToneTitle;
            }
            set {
                this._ModeToneTitle = value;
            }
        }
        
        public virtual object ModeTonePage {
            get {
                return this._ModeTonePage;
            }
            set {
                this._ModeTonePage = value;
            }
        }
        
        public virtual object ModeToneFileName {
            get {
                return this._ModeToneFileName;
            }
            set {
                this._ModeToneFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class ModeToneCollection : System.Collections.CollectionBase {
        
        public virtual ModeTone this[int index] {
            get {
                return ((ModeTone)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(ModeTone Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(ModeTone Item) {
            List.Remove(Item);
        }
    }

