//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Page {
        
        private object _PageID;
        
        private object _PageName;
        
        private object _PageContent;
        
        private object _Ordinal;
        
        private object _PresentationID;
        
        public Page() {
        }
        
        public virtual object PageID {
            get {
                return this._PageID;
            }
            set {
                this._PageID = value;
            }
        }
        
        public virtual object PageName {
            get {
                return this._PageName;
            }
            set {
                this._PageName = value;
            }
        }
        
        public virtual object PageContent {
            get {
                return this._PageContent;
            }
            set {
                this._PageContent = value;
            }
        }
        
        public virtual object Ordinal {
            get {
                return this._Ordinal;
            }
            set {
                this._Ordinal = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class PageCollection : System.Collections.CollectionBase {
        
        public virtual Page this[int index] {
            get {
                return ((Page)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Page Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Page Item) {
            List.Remove(Item);
        }
    }
//}
