//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace terrible1 {
    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Presentation {
        
        private object _PresentationID;
        
        private object _Title;
        
        private object _Description;
        
        private object _ClientID;
        
        public Presentation() {
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
        
        public virtual object Title {
            get {
                return this._Title;
            }
            set {
                this._Title = value;
            }
        }
        
        public virtual object Description {
            get {
                return this._Description;
            }
            set {
                this._Description = value;
            }
        }

        public virtual object ClientID
        {
            get {
                return this._ClientID;
            }
            set {
                this._ClientID = value;
            }
        }
    }
    
    public class PresentationCollection : System.Collections.CollectionBase {
        
        public virtual Presentation this[int index] {
            get {
                return ((Presentation)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Presentation Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Presentation Item) {
            List.Remove(Item);
        }
    }
//}
