//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Sound {
        
        private object _SoundID;
        
        private object _SoundFile;
        
        private object _SoundPath;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;
        
        public Sound() {
        }
        
        public virtual object SoundID {
            get {
                return this._SoundID;
            }
            set {
                this._SoundID = value;
            }
        }
        
        public virtual object SoundFile {
            get {
                return this._SoundFile;
            }
            set {
                this._SoundFile = value;
            }
        }
        
        public virtual object SoundPath {
            get {
                return this._SoundPath;
            }
            set {
                this._SoundPath = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class SoundCollection : System.Collections.CollectionBase {
        
        public virtual Sound this[int index] {
            get {
                return ((Sound)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Sound Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Sound Item) {
            List.Remove(Item);
        }
    }

