//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class TargetMarket {
        
        private object _TargetMarketID;
        
        private object _TargetMarketTitle;
        
        private object _TargetMarketPage;
        
        private object _TargetMarketFileName;
        
        private object _CreatedBy;
        
        private object _CreatedDate;
        
        private object _ModifiedBy;
        
        private object _ModifiedDate;
        
        private object _PresentationID;
        
        public TargetMarket() {
        }
        
        public virtual object TargetMarketID {
            get {
                return this._TargetMarketID;
            }
            set {
                this._TargetMarketID = value;
            }
        }
        
        public virtual object TargetMarketTitle {
            get {
                return this._TargetMarketTitle;
            }
            set {
                this._TargetMarketTitle = value;
            }
        }
        
        public virtual object TargetMarketPage {
            get {
                return this._TargetMarketPage;
            }
            set {
                this._TargetMarketPage = value;
            }
        }
        
        public virtual object TargetMarketFileName {
            get {
                return this._TargetMarketFileName;
            }
            set {
                this._TargetMarketFileName = value;
            }
        }
        
        public virtual object CreatedBy {
            get {
                return this._CreatedBy;
            }
            set {
                this._CreatedBy = value;
            }
        }
        
        public virtual object CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        
        public virtual object ModifiedBy {
            get {
                return this._ModifiedBy;
            }
            set {
                this._ModifiedBy = value;
            }
        }
        
        public virtual object ModifiedDate {
            get {
                return this._ModifiedDate;
            }
            set {
                this._ModifiedDate = value;
            }
        }
        
        public virtual object PresentationID {
            get {
                return this._PresentationID;
            }
            set {
                this._PresentationID = value;
            }
        }
    }
    
    public class TargetMarketCollection : System.Collections.CollectionBase {
        
        public virtual TargetMarket this[int index] {
            get {
                return ((TargetMarket)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(TargetMarket Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(TargetMarket Item) {
            List.Remove(Item);
        }
    }

