//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Text;
    using System.Data;
    using System.Data.SqlClient;
    
    
    public class Users {
        
        private object _UserID;
        
        private object _UserName;
        
        private object _Password;
        
        private object _FirstName;
        
        private object _LastName;

        private object _RoleID;

        private object _CompanyID;

        private object _Email;
        private object _Role;

        private object _ClientID;

        public Users() {
        }
        
        public virtual object UserID {
            get {
                return this._UserID;
            }
            set {
                this._UserID = value;
            }
        }
        public virtual object Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this._Role = value;
            }
        }
        
        public virtual object UserName {
            get {
                return this._UserName;
            }
            set {
                this._UserName = value;
            }
        }
        
        public virtual object Password {
            get {
                return this._Password;
            }
            set {
                this._Password = value;
            }
        }
        
        public virtual object FirstName {
            get {
                return this._FirstName;
            }
            set {
                this._FirstName = value;
            }
        }
        
        public virtual object LastName {
            get {
                return this._LastName;
            }
            set {
                this._LastName = value;
            }
        }

        public virtual object CompanyID
        {
            get {
                return this._CompanyID;
            }
            set {
                this._CompanyID = value;
            }
        }

        public virtual object ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this._ClientID = value;
            }
        }
        public virtual object RoleID
        {
            get
            {
                return this._RoleID;
            }
            set
            {
                this._RoleID = value;
            }
        }
        public virtual object Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }
    }
    
    public class UsersCollection : System.Collections.CollectionBase {
        
        public virtual Users this[int index] {
            get {
                return ((Users)(List[index]));
            }
            set {
                List[index] = value;
            }
        }
        
        public virtual void Add(Users Item) {
            List.Add(Item);
        }
        
        public virtual void Remove(Users Item) {
            List.Remove(Item);
        }
    }

